/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Warm Café & Literatur Community Design System Tokens
        surface: {
          DEFAULT: '#FAF6EE',
          paper: '#FDFBF7',
          dim: '#DED9D7',
          bright: '#FEF8F6',
          lowest: '#FFFFFF',
          low: '#F5EFEB',
          container: '#F2ECE4',
          high: '#EAE2D8',
          highest: '#E2D8CC',
          dark: '#181615',
          'dark-surface': '#24201E',
          'dark-container': '#2C2825',
          'dark-high': '#363230',
        },
        'on-surface': {
          DEFAULT: '#1D1B1A',
          variant: '#5B403D',
        },
        'inverse-surface': {
          DEFAULT: '#32302F',
          on: '#F5F0EE',
        },
        outline: {
          DEFAULT: '#8C706B',
          variant: '#E2D0CB',
          dark: '#4A423F',
        },
        primary: {
          DEFAULT: '#8B1E2D', // Deep Polish Carmine / Wine Red (WCAG AA > 6:1 on #FAF6EE)
          hover: '#6E1420',
          dark: '#FF758F',
          container: '#8B1E2D',
          'on-container': '#FFFFFF',
          fixed: '#FFDAD6',
          'fixed-dim': '#FFB3AC',
        },
        secondary: {
          DEFAULT: '#5E5E5C',
          container: '#E1DFDC',
          'on-container': '#636360',
        },
        tertiary: {
          DEFAULT: '#3B6B35', // Warm Olive / Sage Green
          dark: '#78B871',
          container: '#2D5428',
          'on-container': '#FDFFF7',
        },
        accent: {
          'wine-red': '#8B1E2D',
          'cafe-cream': '#FAF6EE',
          'cafe-paper': '#FDFBF7',
          'amber-honey': '#D97706',
          'olive-green': '#3B6B35',
          'wood-dark': '#3E2723',
          'wood-light': '#5D4037',
          'wood-shelf': '#8D6E63',
          'paper-white': '#FFFFFF',
        },
        brand: {
          primary: '#8B1E2D',
          'primary-hover': '#6E1420',
          'primary-light': '#FF758F',
          secondary: '#3B6B35',
          'secondary-hover': '#2D5428',
          'secondary-light': '#78B871',
          amber: '#D97706',
          'amber-hover': '#B45309',
          marker: '#F2B705',
          'marker-text': '#1D1B1A',
          bg: '#FAF6EE',
          'bg-dark': '#181615',
          surface: '#FFFFFF',
          'surface-light': '#F5EFEB',
          'surface-dark': '#24201E',
          card: '#FFFFFF',
          'card-dark': '#24201E',
          text: '#1D1B1A',
          'text-muted': '#5B403D',
          'text-dark': '#F5F0EE',
          'text-muted-dark': '#D4C5C2',
          border: '#E2D8CC',
          'border-dark': '#363230',
          focus: '#8B1E2D',
        }
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Open Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['"Literata"', '"Lora"', 'Georgia', 'serif'],
        heading: ['"Literata"', '"Lora"', 'Georgia', 'serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
        card: '1.25rem',
        ticket: '1rem',
        button: '9999px',
        pill: '9999px',
      },
      boxShadow: {
        tactile: '0 4px 20px rgba(51, 49, 48, 0.06)',
        'tactile-hover': '0 8px 30px rgba(51, 49, 48, 0.12)',
        ticket: '0 6px 24px rgba(42, 36, 33, 0.08)',
        wood: 'inset 0 2px 4px rgba(0,0,0,0.4), 0 8px 20px rgba(0,0,0,0.25)',
        shelf: '0 12px 28px rgba(30, 20, 15, 0.35)',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1200px',
      }
    },
  },
  plugins: [],
}
